version: '3.8'

services:
  backend:
    image: project-manager-app-backend:latest
    container_name: project-manager-app-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    image: project-manager-app-frontend:latest
    container_name: project-manager-app-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081/api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
